project:
  type: book

execute: 
  freeze: auto
  cache: true

jupyter: python3

book:
  title: "大模型平台和应用实例"
  author: "高春辉"
  date: now
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - huggingface.qmd
    - huggingface-models.qmd
    - chatanywhere.qmd
    - moonshot-kimi.qmd
    - bigmodel.qmd
    - grounding-dino.qmd
    - langchain-chatchat.qmd
    - openai.qmd
    - coze.qmd
    - bailian.qmd
    - volcengine.qmd
    - research-summary.qmd
    - object-detection-of-microfluidic-chip.qmd
    - gradio.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-width: 5.5
    fig-asp: 0.618
    warning: false
    message: false
  pdf:
    documentclass: scrreprt
    fig-width: 5.5
    fig-asp: 0.618
    warning: false
    message: false
    include-in-header: 
          text: |
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
